### ISSUE TITLE
snyk --version not working in v1.279.1

### ISSUE THREAD

**Issue by joselcc** [snyk/snyk#969]
- `node -v`: v12.14.0
- `npm -v`: v6.13.4
- `snyk -v`: 1.279.1
- Command run:
`snyk -v` or `snyk --version`

### Expected behaviour
Current version ` 1.279.1` is printed out in the console.

### Actual behaviour
The following message is printed out:
```module is not a function```

### Steps to reproduce
* Install snyk globally: `npm i snyk@1.279.1 --global`
* Run snyk with version option:  `snyk -v` or `snyk --version`

---
output for `snyk --version --debug` is attached
[debug.log](https://github.com/snyk/snyk/files/4106352/debug.log)

**Comment by lili2311** [comment]
Thanks for reporting this, taking a 👀 now

**Comment by lili2311** [comment]
Fix has been merged, please try version `1.281.1`

**Comment by joselcc** [comment]
thanks @lili2311
