### ISSUE TITLE
[🐛] Cannot find module 'legacy-snyk-docker-plugin'

### ISSUE THREAD

**Issue by orsinium** [snyk/snyk#1453]
- `node -v`: `10.21.0`
- `npm -v`: -
- `snyk -v`: `1.413.0 `
- OS: debian buster
- Command run: `snyk auth $SNYK_TOKEN`

### Expected behaviour

It works on Snyk 1.411.0 without exceptions but fails on 1.413.0.

### Actual behaviour

```
$ npm install -g snyk
/usr/local/bin/snyk -> /usr/local/lib/node_modules/snyk/dist/cli/index.js
+ snyk@1.413.0
added 451 packages from 327 contributors in 44.743s
$ snyk auth $SNYK_TOKEN
Error: Cannot find module 'legacy-snyk-docker-plugin'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/snyk/src/lib/plugins/index.ts:1:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

### Steps to reproduce

Gitlab CI job:

```
snyk:
  image: "python:3.6-buster"
  before_script:
    - cp -r ./venv $VENV_PATH
    - apt-get update
    - apt-get install -y -q nodejs npm
    - npm install -g snyk
    - snyk auth $SNYK_TOKEN
```

### Debug log

-

### Screenshots

![image](https://user-images.githubusercontent.com/9638362/95585124-136c1580-0a3f-11eb-85e9-3ad0462c79fd.png)

**Comment by JackuB** [comment]
Hi, I'm running the exactly same version on the same Node and I can't replicate this issue so far.

My npm log was a bit different on the install step:
`added 465 packages from 327 contributors in 28.211s`

Wondering what could've caused this? Any chance you are using custom registry? Or something else that could influence it?

**Comment by Properko** [comment]
Happens to me as well when running `snyk protect` inside `circleci` steps.
node: `12.18.4`
snyk: `1.413.0`

Pinning the snyk version back to `1.412.0` resolves the issue.

**Comment by apaleslimghost** [comment]
we're encountering the same issue running `snyk monitor`. no custom registry, it was installed with npm v5.7.0.

i haven't been able to verify this, but i wonder if it's something that's changed between npm v5 and v6 to do with installing packages from git, because the [name in `snyk`'s `dependencies`](https://github.com/snyk/snyk/blob/master/package.json#L80) is different from the [name in `snyk-docker-plugin`'s `package.json`](https://github.com/snyk/snyk-docker-plugin/blob/master/package.json#L2)

**Comment by paulrostorp** [comment]
I think this introduces the bug https://github.com/snyk/snyk/commit/bf32c4c837b2a972f2e18ad01be81e388061551f

**Comment by JackuB** [comment]
Yes, it's definitely an incompatibility with npm@5. All our pipelines are using the npm@6.
We're looking into possible solutions.

**Comment by bvandermeersch** [comment]
will this be addressed today?

**Comment by cubimon** [comment]
I have the same issue in azure devops ci with the SnykSecurityScan@0 task on ubuntu-latest

**Comment by JackuB** [comment]
Latest release https://github.com/snyk/snyk/releases/tag/v1.413.1 seems to be working with npm@v5
If your CI scripts are using latest CLI, they should pick that change up on the next run

**Comment by cubimon** [comment]
if v1.413.1 contains the fix, it still doesn't work. I still the same error:
```
/usr/bin/sudo npm install -g snyk snyk-to-html
/usr/local/bin/snyk-to-html -> /usr/local/lib/node_modules/snyk-to-html/dist/index.js
/usr/local/bin/snyk -> /usr/local/lib/node_modules/snyk/dist/cli/index.js
+ snyk@1.413.1
+ snyk-to-html@1.14.0
added 487 packages from 336 contributors in 28.808s

/usr/local/bin/snyk auth ***
Error: Cannot find module '/usr/local/lib/node_modules/snyk/node_modules/legacy-snyk-docker-plugin/dist/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:321:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:682:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:952:27)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/snyk/src/lib/plugins/index.ts:1:1)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)

```

**Comment by Properko** [comment]
> if v1.413.1 contains the fix, it still doesn't work. I still the same error:

likewise, our ci steps run with node `12.18.4` bundled with npm `6.14.6`, so the issue was not constrained only to npm@5

**Comment by bvandermeersch** [comment]
I am still receiving the error:

 yarn install --production=true
yarn install v1.22.4
info No lockfile found.
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/5] Validating package.json...
[2/5] Resolving packages...
warning coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
warning cognito-express > request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
warning cognito-express > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning cognito-express > request > har-validator@5.1.5: this library is no longer supported
warning hellosign-sdk > expect > jest-message-util > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning hellosign-sdk > expect > jest-message-util > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning hubspot > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning hubspot > request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
warning pdfmake > pdfkit > fontkit > babel-runtime > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning prerender-node > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
warning sequelize-redis-cache > circular-json@0.3.0: CircularJSON is in maintenance only, flatted is its successor.
error Can't add "legacy-snyk-docker-plugin": invalid package version undefined.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by JackuB** [comment]
Interesting that our CI pipeline, nor our [Smoke tests](https://github.com/snyk/snyk/runs/1231920766) are picking this up. We couldn't reproduce it so far with the latest version.

**Comment by JackuB** [comment]
@bvandermeersch the yarn install issue was reproduced and is now fixed, as the package.json now contains a valid semver version https://github.com/snyk/snyk-docker-plugin/blob/chore/fix-v3.26.2/package.json#L6

<img width="483" alt="Screenshot 2020-10-09 at 17 19 03" src="https://user-images.githubusercontent.com/1788727/95601288-8a130e00-0a53-11eb-962b-da9b491b9fa2.png">

**Comment by bvandermeersch** [comment]
Thank you for qucik fixes and responses. I have tested and can verify it is now working.

**Comment by mweinand** [comment]
I am also experiencing this still with the latest Azure DevOps Snyk plugin.  
```
==============================================================================
Task         : Snyk Security Scan
Description  : Azure Pipelines Task for Snyk
Version      : 0.2.11
Author       : Snyk
Help         : 
==============================================================================
/usr/bin/sudo npm install -g snyk snyk-to-html
/usr/local/bin/snyk-to-html -> /usr/local/lib/node_modules/snyk-to-html/dist/index.js
/usr/local/bin/snyk -> /usr/local/lib/node_modules/snyk/dist/cli/index.js
+ snyk-to-html@1.14.0
+ snyk@1.413.1
added 487 packages from 336 contributors in 39.388s

/usr/local/bin/snyk auth ***
Error: Cannot find module '/usr/local/lib/node_modules/snyk/node_modules/legacy-snyk-docker-plugin/dist/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:321:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:682:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:952:27)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/snyk/src/lib/plugins/index.ts:1:1)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
```

**Comment by aboyce** [comment]
Also seeing the `"main" entry` issue for the original package:

```
Error: Cannot find module '/*****/node_modules/legacy-snyk-docker-plugin/dist/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:321:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:534:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:27)
    at Function.Module._load (internal/modules/cjs/loader.js:743:27)
    at Module.require (internal/modules/cjs/loader.js:965:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/*****/node_modules/snyk/src/lib/plugins/index.ts:1:1)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:941:32)
```

**Comment by JackuB** [comment]
We'll be reverting the change that introduced the `legacy-snyk-docker-plugin` and releasing a new version

**Comment by mweinand** [comment]
Confirmed snyk@1.413.2 fixed this for our organization.
