### PR TITLE
fix: use lodash fork

### PR DESCRIPTION
**Pull request by lili2311**
- [x] Ready for review
- [x] Follows [CONTRIBUTING](https://github.com/snyk/snyk/blob/master/.github/CONTRIBUTING.md) rules
- [x] Reviewed by Snyk internal team

#### What does this PR do?
Use lodash fork, regression introduced in https://github.com/snyk/snyk/pull/1183

### CODE REVIEW

**Comment by rictorres** [comment]
So this is what's causing the following error, right?

```
Error: Cannot find module 'lodash'
...
```
