### ISSUE TITLE
[🐛] CLI returns exit code 1 when an error is encountered

### ISSUE THREAD

**Issue by mikehepple** [snyk/snyk#1457]
- `node -v`: `v12.18.4`
- `npm -v`: `6.14.6`
- `snyk -v`: `1.413.1`
- OS: Alpine
- Command run: any (`snyk test`)

### Expected behaviour
When an error is encountered we would expect an error code 2 based on the docs:

```
Possible exit statuses and their meaning:

  - 0: success, no vulns found
  - 1: action_needed, vulns found
  - 2: failure, try to re-run command
  - 3: failure, no supported projects detected
```

### Actual behaviour
When encountering an error the CLI returns a 1 meaning we cannot differentiate from the "vulns found" status.

### Steps to reproduce
Use a Snyk CLI version that throws an error (e.g. `1.413.0`)

### Debug log
n/a

### Screenshots
n/a

**Comment by JackuB** [comment]
@mikehepple hey, we can take a look at that - got some example of an error that you've seen ending with exit 1? e.g. network errors, auth errors? 
Tested it with few errors I've triggered and it seems that I'm getting the correct one.

**Comment by mikehepple** [comment]
Sorry thought I'd included that 🤦‍♂️

We experienced this during the issues introduced in #1453 

You can see the exit code in the screenshot provided by the originator

**Comment by JackuB** [comment]
Ah, in case of #1453, the exit code happened even before the CLI ran - the `Error: Cannot find module '___'` is coming from Node internals, thus we have no control over that. Don't think there is anything we can do there, apart from making sure that CLI release is in a healthy state. Maybe we could instantiate UncaughtException handler early on 🤔 I'll be posting a post-mortem on the #1453 issue later.

**Comment by lili2311** [comment]
@mikehepple can this issue be closed? Does the answer above answer your query?
