### ISSUE TITLE
[🐛] TypeScript type error after upgrade Snyk to v1.359.0

### ISSUE THREAD

**Issue by kopach** [snyk/snyk#1266]
- `node -v`: 11.15.0
- `npm -v`: 6.7.0
- `snyk -v`: 1.361.3 (reproducible starting from v1.359.0 )
- OS: OSX, Linux (probably Windows as well)
- Command run: `tsc --sourceMap false`

### Expected behaviour
Projects builds successfully

### Actual behaviour
Build on [karma-sabarivka-reporter](https://github.com/kopach/karma-sabarivka-reporter) using `tsc` command fails with error: 

```
node_modules/@types/emscripten/index.d.ts(53,33): error TS2304: Cannot find name 'WebGLRenderingContext'.
node_modules/@types/emscripten/index.d.ts(67,28): error TS2304: Cannot find name 'MessageEvent'.
```

### Steps to reproduce

1. clone https://github.com/kopach/karma-sabarivka-reporter project
2. run npm install
3. run `npm run build`
4. everything should build successfully
5. switch to branch `renovate/snyk-1.x` (details: https://github.com/kopach/karma-sabarivka-reporter/pull/144)
6. run `npm install`
7. run `npm run build`
8. error is reproducible 

### Debug log
https://travis-ci.com/github/kopach/karma-sabarivka-reporter/jobs/359983635

**Comment by dkontorovskyy** [comment]
Hey, @kopach.
What happens if you add "dom" to "lib" array in `tsconfig.ts`

**Comment by kopach** [comment]
Hey, @dkontorovskyy, I'll try it out and let you know. However, note, that `karma-sabarivka-reporter` tool doesn't have dependency upon DOM. It doesn't manipulate over DOM.

**Comment by kopach** [comment]
Hey @dkontorovskyy, workaround didn't help.

**Comment by dkontorovskyy** [comment]
@kopach can you try not capitalize libs? Use `es5` and `dom`. Maybe this is an issue?

**Comment by kopach** [comment]
@dkontorovskyy, same result. See commit from above https://github.com/kopach/karma-sabarivka-reporter/commit/df106b19d60d3563289d1035bfb07f02e06a7732

**Comment by lili2311** [comment]
👋 @kopach I am able to successfully upograde & build your project by making this change to the `tsconfig.json`

Unfortunately an upstream dependency introduced this and we had to make the same change to build TS.
```        
"lib": [
    "es2017",
     "dom"
 ],
```
<img width="488" alt="Screen Shot 2020-08-10 at 16 50 13" src="https://user-images.githubusercontent.com/2911613/89802569-94835b00-db29-11ea-8d02-cdd9c7395d81.png">

**Comment by kopach** [comment]
Hi @lili2311. Thanks for your help. Unfortunately, with last update for snyk to  v1.374.0 – your workaround doesn't seem to work. You may check it out here https://github.com/kopach/karma-sabarivka-reporter/pull/144/checks?check_run_id=986733808

**Comment by lili2311** [comment]
hi @kopach you needed to manually update the renovate PR like this https://github.com/kopach/karma-sabarivka-reporter/pull/184 the issue is with typescript configuration and this won't be updated automatically by renovate for you. I am not sure if the tests will run since the PR is from a fork but please use that.

**Comment by kopach** [comment]
hi @lili2311. Thanks for your help. I finally managed to make it working. Basically, after your workaround merged - new issue appeared - tests started to fail on Node v11 due to fact that JS was running out of memory (I expect this is because more JS code was added to runtime with DOM lib). You can check details here https://github.com/kopach/karma-sabarivka-reporter/runs/1004638236
To fix that I had to add another workaround and increase JS memory allocation limit https://github.com/kopach/karma-sabarivka-reporter/pull/187. Now everything works fine. 
For me, those workarounds are more than acceptable for this project. We can close this issue.
Thank you once again.

**Comment by TimMensch** [comment]
I'm working on a server component that does NOT have `dom`, but `synk` is breaking my build.

Not interested in adding `dom` and the related compile-time overhead to my project. Please fix ASAP. Not sure why it's _closed_ when the bug isn't actually _fixed_.

**Comment by lili2311** [comment]
@TimMensch we had to add it as a third party library Yarn requires it too which was breaking our build in turn! We need to use the Yarn package for our Yarn support unfortunately.

**Comment by kopach** [comment]
@TimMensch, I've closed this issue as workaround provided was fine enough for my small open source project. However, I do agree this is not how things should be done. 
@lili2311, any chance you could raise this issue to Yarn project and link it here if this is issue with Yarn and not Snyk?
